# Generated by Django 5.2.16 on 2026-07-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('contenttypes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='EN_PROGRESO', max_length=16)),
            ],
            options={
                'ordering': ['pipeline', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('telefono_normalizado', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('origen', models.CharField(choices=[('whatsapp_directo', 'WhatsApp directo'), ('catalogo_rfq', 'RFQ desde catálogo'), ('referido', 'Referido'), ('manual', 'Ingreso manual')], default='manual', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('primera_respuesta', models.DateTimeField(blank=True, help_text='KPI: tiempo hasta la primera respuesta del equipo.', null=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to='usuarios.agente')),
                ('cliente', models.ForeignKey(blank=True, help_text='Se vincula cuando el lead coincide con un cliente ya registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clientes.cliente')),
                ('marca_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clientes.marca')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_cierre_real', models.DateTimeField(blank=True, null=True)),
                ('motivo_perdida', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_creadas', to=settings.AUTH_USER_MODEL)),
                ('etapa_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='oportunidades.etapa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='oportunidades.lead')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='oportunidades.pipeline')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='oportunidades.pipeline'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('tarea', 'Tarea')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Solo para tareas: cuándo ejecutar.', null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='usuarios.agente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='actividad_objeto_idx')],
            },
        ),
        migrations.CreateModel(
            name='CambioEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_etapa', to='usuarios.agente')),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oportunidades.etapa')),
                ('etapa_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oportunidades.etapa')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='oportunidades.oportunidad')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['oportunidad', 'timestamp'], name='cambio_opp_fecha_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['lead', 'etapa_actual'], name='oportunidad_lead_etapa_idx'),
        ),
        migrations.AddConstraint(
            model_name='etapa',
            constraint=models.UniqueConstraint(fields=('pipeline', 'orden'), name='etapa_orden_unico_por_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='etapa',
            constraint=models.UniqueConstraint(fields=('pipeline', 'nombre'), name='etapa_nombre_unico_por_pipeline'),
        ),
    ]
