# Generated by Django 5.2.16 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('tarea', 'Tarea')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Solo para tareas: cuándo ejecutar.', null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CambioEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='EN_PROGRESO', max_length=16)),
            ],
            options={
                'ordering': ['pipeline', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('telefono_normalizado', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('origen', models.CharField(choices=[('whatsapp_directo', 'WhatsApp directo'), ('catalogo_rfq', 'RFQ desde catálogo'), ('referido', 'Referido'), ('manual', 'Ingreso manual')], default='manual', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('primera_respuesta', models.DateTimeField(blank=True, help_text='KPI: tiempo hasta la primera respuesta del equipo.', null=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_cierre_real', models.DateTimeField(blank=True, null=True)),
                ('motivo_perdida', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
