# Generated by Django 5.2.16 on 2026-07-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('contenttypes', '0001_initial'),
        ('oportunidades', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_etapa', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='etapa_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oportunidades.etapa'),
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='etapa_nueva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oportunidades.etapa'),
        ),
        migrations.AddField(
            model_name='lead',
            name='agente_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Se vincula cuando el lead coincide con un cliente ya registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='marca_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clientes.marca'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etapa_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='oportunidades.etapa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='oportunidades.lead'),
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='oportunidades.oportunidad'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='oportunidades.pipeline'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='oportunidades.pipeline'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['content_type', 'object_id'], name='actividad_objeto_idx'),
        ),
        migrations.AddIndex(
            model_name='cambioetapa',
            index=models.Index(fields=['oportunidad', 'timestamp'], name='cambio_opp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['lead', 'etapa_actual'], name='oportunidad_lead_etapa_idx'),
        ),
        migrations.AddConstraint(
            model_name='etapa',
            constraint=models.UniqueConstraint(fields=('pipeline', 'orden'), name='etapa_orden_unico_por_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='etapa',
            constraint=models.UniqueConstraint(fields=('pipeline', 'nombre'), name='etapa_nombre_unico_por_pipeline'),
        ),
    ]
