# Generated by Django 5.2.16 on 2026-07-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_programada',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
