# Generated by Django 5.2.16 on 2026-07-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0003_remove_actividad_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='probabilidad_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Probabilidad de cierre en esta etapa (0–100). Usado en el forecast del dashboard.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Contexto del trato: qué necesita, urgencia, condiciones especiales.'),
        ),
    ]
