# Generated by Django 5.2.16 on 2026-07-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('correo', 'Correo'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=5)),
                ('notas', models.TextField(blank=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='usuarios.agente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to='usuarios.agente')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tarea_objeto_idx'), models.Index(fields=['estado', 'fecha_vencimiento'], name='tarea_estado_fecha_idx')],
            },
        ),
    ]
