# Generated by Django 5.2.16 on 2026-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('TECNICO', 'Soporte técnico'), ('SUPERVISOR', 'Supervisor de ventas'), ('GERENTE', 'Gerente'), ('ADMIN_CRM', 'Administrador CRM')], default='VENDEDOR', max_length=20),
        ),
    ]
