# Generated by Django 5.2.16 on 2026-07-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('cotizaciones', '0001_initial'),
        ('oportunidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=16)),
                ('proveedor', models.CharField(choices=[('SIN_INTEGRAR', 'Sin integrar'), ('META_CLOUD_API', 'Meta Cloud API'), ('TWILIO', 'Twilio')], default='SIN_INTEGRAR', max_length=20)),
                ('proveedor_numero_id', models.CharField(blank=True, max_length=100)),
                ('proveedor_cuenta_id', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=30)),
                ('cuerpo', models.TextField()),
                ('variables', models.JSONField(default=list, help_text='Lista de nombres de variables en el cuerpo.')),
                ('aprobada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=16)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('ABIERTA', 'Abierta'), ('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor_conversation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ventana_expira_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='cotizaciones.cotizacion')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='oportunidades.lead')),
                ('oportunidad_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_activas', to='oportunidades.oportunidad')),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.numerowhatsapp')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.sede')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Cliente'), ('SALIENTE', 'Equipo')], max_length=10)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('proveedor_message_id', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('UBICACION', 'Ubicación'), ('PLANTILLA', 'Plantilla')], default='TEXTO', max_length=12)),
                ('estado_entrega', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_media_id', models.CharField(blank=True, max_length=150)),
                ('url_temporal', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='whatsapp.mensajewhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='EventoWebhookWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('SIN_INTEGRAR', 'Sin integrar'), ('META_CLOUD_API', 'Meta Cloud API'), ('TWILIO', 'Twilio')], max_length=20)),
                ('evento_id_proveedor', models.CharField(blank=True, db_index=True, max_length=150)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.numerowhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='AgenteNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('titular', 'Titular / Ventas'), ('soporte', 'Soporte / Backup'), ('supervisor', 'Supervisor')], default='titular', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_asignados', to='usuarios.agente')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_asignados', to='whatsapp.numerowhatsapp')),
            ],
        ),
        migrations.AddField(
            model_name='numerowhatsapp',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeros_whatsapp', to='whatsapp.sede'),
        ),
        migrations.AddConstraint(
            model_name='mensajewhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('proveedor_message_id', ''), _negated=True), fields=('conversacion', 'proveedor_message_id'), name='mensaje_whatsapp_idempotente_por_proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='agentenumero',
            unique_together={('agente', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='numerowhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('proveedor_numero_id', ''), _negated=True), fields=('proveedor', 'proveedor_numero_id'), name='numero_whatsapp_identidad_externa_unica_por_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('sede', 'telefono'), name='conversacion_unica_por_sede_telefono'),
        ),
    ]
