# Generated by Django 5.2.16 on 2026-07-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_segmento'),
        ('cotizaciones', '0002_cotizacion_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('ABIERTA', 'Abierta'), ('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='cotizaciones.cotizacion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.sede')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Cliente'), ('SALIENTE', 'Equipo')], max_length=10)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('proveedor_message_id', models.CharField(blank=True, max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('sede', 'telefono'), name='conversacion_unica_por_sede_telefono'),
        ),
    ]
