# Generated by Django 5.2.16 on 2026-07-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_media_id', models.CharField(blank=True, max_length=150)),
                ('url_temporal', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoWebhookWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('SIN_INTEGRAR', 'Sin integrar'), ('META_CLOUD_API', 'Meta Cloud API'), ('TWILIO', 'Twilio')], max_length=20)),
                ('evento_id_proveedor', models.CharField(blank=True, db_index=True, max_length=150)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=16)),
                ('proveedor', models.CharField(choices=[('SIN_INTEGRAR', 'Sin integrar'), ('META_CLOUD_API', 'Meta Cloud API'), ('TWILIO', 'Twilio')], default='SIN_INTEGRAR', max_length=20)),
                ('proveedor_numero_id', models.CharField(blank=True, max_length=100)),
                ('proveedor_cuenta_id', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='oportunidad_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_activas', to='oportunidades.oportunidad'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='proveedor_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ventana_expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='estado_entrega',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], max_length=12),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('DOCUMENTO', 'Documento'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('UBICACION', 'Ubicación'), ('PLANTILLA', 'Plantilla')], default='TEXTO', max_length=12),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='telefono',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='mensajewhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('proveedor_message_id', ''), _negated=True), fields=('conversacion', 'proveedor_message_id'), name='mensaje_whatsapp_idempotente_por_proveedor'),
        ),
        migrations.AddField(
            model_name='adjuntowhatsapp',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='whatsapp.mensajewhatsapp'),
        ),
        migrations.AddField(
            model_name='numerowhatsapp',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeros_whatsapp', to='whatsapp.sede'),
        ),
        migrations.AddField(
            model_name='eventowebhookwhatsapp',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.numerowhatsapp'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.numerowhatsapp'),
        ),
        migrations.AddConstraint(
            model_name='numerowhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('proveedor_numero_id', ''), _negated=True), fields=('proveedor', 'proveedor_numero_id'), name='numero_whatsapp_identidad_externa_unica_por_proveedor'),
        ),
    ]
