# Generated by Django 5.2.16 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_entidad', models.CharField(choices=[('NATURAL', 'Persona natural'), ('EMPRESA', 'Empresa / RUC')], default='NATURAL', max_length=10)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_normalizado', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('segmento', models.CharField(choices=[('MOSTRADOR', 'Mostrador / retail'), ('TALLER', 'Taller mecánico'), ('DISTRIBUIDOR', 'Distribuidor / mayorista'), ('SEGUROS', 'Aseguradora'), ('FLOTA', 'Empresa con flota'), ('CONCESIONARIO', 'Concesionario'), ('GOBIERNO', 'Entidad de gobierno')], default='MOSTRADOR', max_length=20)),
                ('etapa_ciclo', models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('LEAD', 'Lead'), ('CLIENTE', 'Cliente'), ('RECURRENTE', 'Recurrente')], default='LEAD', max_length=12)),
                ('estado_lead', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('EN_CONTACTO', 'En contacto'), ('CALIFICADO', 'Calificado'), ('NO_CALIFICADO', 'No calificado')], max_length=14, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('MOSTRADOR', 'Mostrador')], max_length=20)),
                ('nota', models.CharField(max_length=280)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
