# Generated by Django 5.2.16 on 2026-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_normalizado', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('segmento', models.CharField(choices=[('CONSUMO', 'Consumo / mostrador'), ('CORPORATIVO', 'Corporativo'), ('SEGUROS', 'Seguros'), ('TALLER', 'Taller')], default='CONSUMO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('MOSTRADOR', 'Mostrador')], max_length=20)),
                ('nota', models.CharField(max_length=280)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
