# Generated by Django 5.2.16 on 2026-07-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('segmento', models.CharField(choices=[('CONSUMO', 'Consumo / mostrador'), ('CORP_MAYOR', 'Corporativo por mayor'), ('CORP_GIRO', 'Corporativo mismo giro')], default='CONSUMO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('MOSTRADOR', 'Mostrador')], max_length=20)),
                ('nota', models.CharField(max_length=280)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
        ),
    ]
