# Generated by Django 5.2.16 on 2026-07-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_creado_por_vehiculo_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(choices=[('CONSUMO', 'Consumo / mostrador'), ('CORPORATIVO', 'Corporativo'), ('SEGUROS', 'Seguros'), ('TALLER', 'Taller')], default='CONSUMO', max_length=20),
        ),
    ]
