# Generated by Django 5.2.16 on 2026-07-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion_repuesto', models.TextField()),
                ('codigo_producto', models.CharField(blank=True, max_length=50)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('CONVERTIDA', 'Convertida'), ('PERDIDA', 'Perdida')], default='ENVIADA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
