# Generated by Django 5.2.16 on 2026-07-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion_repuesto', models.TextField()),
                ('codigo_producto', models.CharField(blank=True, max_length=50)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('CONVERTIDA', 'Convertida'), ('PERDIDA', 'Perdida')], default='ENVIADA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='oportunidades.oportunidad')),
                ('reemplazada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='cotizaciones.cotizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='cot_usuario_estado_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('descuento_pct__gte', 0), ('descuento_pct__lte', 100)), name='cotizacion_descuento_pct_entre_0_y_100'), models.UniqueConstraint(condition=models.Q(('vigente', True), ('oportunidad__isnull', False)), fields=('oportunidad',), name='una_cotizacion_vigente_por_oportunidad')],
            },
        ),
    ]
