# Generated by Django 5.2.16 on 2026-07-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
