# Generated by Django 5.2.16 on 2026-07-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='oportunidades.oportunidad'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='reemplazada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='cotizaciones.cotizacion'),
        ),
    ]
