# Generated by Django 5.2.16 on 2026-07-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['usuario', 'estado'], name='cot_usuario_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_pct__gte', 0), ('descuento_pct__lte', 100)), name='cotizacion_descuento_pct_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True), ('oportunidad__isnull', False)), fields=('oportunidad',), name='una_cotizacion_vigente_por_oportunidad'),
        ),
    ]
